### ISSUE TITLE
Some errors and suggestions for 6.1-3 and 6.6

### ISSUE THREAD

**Issue by th28** [alexjungaalto/MachineLearningTheBasics#1]
Hi Alex,

I'm a student on the ML course. Attached are a few annotations I made when doing the required reading for Round 6. Some of them are purely stylistic in nature so not sure how useful this is. Anyway thought I'd attach it here just in case. For reference all my corrections/annotations occur on pages 105 - 119 and pages 124 -125.

[MLBasicsBook_annotated.pdf](https://github.com/alexjungaalto/MachineLearningTheBasics/files/6069428/MLBasicsBook_annotated.pdf)

**Comment by alexjungaalto** [comment]
Thx a lot Tom!
