### ISSUE TITLE
Baseline accuracy is not covered

### ISSUE THREAD

**Issue by ptrktn** [alexjungaalto/MachineLearningTheBasics#2]
If you search the current draft with "baseline", no phrases are found. Therefore this issue.

It would be a nice improvement to include a section on the topic of baseline accuracy. Like why it is required, how it can created for a specific problem types and how it is utilised.

**Comment by alexjungaalto** [comment]
Thx for the very relevant suggestion. I have mainly used the term "benchmark" in the book but now I added also the term "baseline". Let me know if you find that there is sufficient discussion of baselines for the evaluation of ML methods.

**Comment by ptrktn** [comment]
Thanks for updating the text. Now it is easy to find where the topic is covered. The term baseline is more correct in machine learning context. Using the term benchmark may be too easily perceived as nonfunctional feature, like how fast the method calculates the result, which is has nothing to do with accuracy. It would be a good improvement to include a section to walk the reader through what baseline is, why it matters, and how to build one for different type of machine learning tasks. I ought to comment less and write up something instead. If I can come up with a decent text, I share it here.
